spring:
 application:
  name: "account"
 datasource:
  url: jdbc:h2:mem:accountsdb
  driver-class-name: org.h2.Driver
  username: "sa"
  password: ""
 h2:
  console:
   enabled: true
   path: /h2-console
 config:
  import: "configserver:http://localhost:8000"
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 sql:
  init:
   mode: always
 profiles:
  active: "default"
 cloud:
  openfeign:
    circuitbreaker:
      enabled: true
  function:
    definition: ReceiveMessage
  stream:
    kafka:
      binder:
        brokers: localhost:9092
    bindings:
      sendMessage-out-0:
        destination: Send-message
      ReceiveMessage-in-0:
        destination: receive-message
        group: ${spring.application.name}

 data:
   redis:
    host: localhost
    port: 6379
    password: admin
    timeout: 60000


management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
   readiness-state:
     enabled: true
   liveness-state:
     enabled: true
 endpoint:
  shutdown:
   access: unrestricted
  health:
    probes:
      enabled: true
 info:
  env:
   enabled: true

eureka:
 instance:
  prefer-ip-address: true
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   defaultZone: "http://localhost:8500/eureka/"

info:
 app:
  name: "accounts"
  description: "Eazy Bank Accounts Application"
  version: "1.0.0"

logging:
  level:
    org:
      bankapp: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10000
        failure-rate-threshold: 50
    instances:
      LOANS:
        base-config: default
      CARDS:
        base-config: default