{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .value.deploymentName }}
  labels:
    app: {{ .value.appLabel }}
spec:
  replicas: {{ .value.replicaCount }}
  selector:
    matchLabels:
      app: {{ .value.appLabel }}
  template:
    metadata:
      Labels:
        app: {{ .value.appLabel }}
    spec:
      containers:
        - name: {{ .value.appLabel}}
          image: {{ .value.image.repoName}}:{{.value.image.tag}}
          ports:
            containerPort: {{ .value.containerPort}}
            protocol: TCP
          env:
            {{- if .Values.appName_enable }}
            - name: SPRING_APPLICATION_NAME
              value: {{ .Values.appName}}
            {{- end }}
            {{- if Values.profile_enable }}
            - name: SPRING_PROFILE_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap}}
                  key: SPRING_PROFILE_ACTIVE
            {{- end }}
            {{- if Values.config_enable }}
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: SPRING_CONFIG_IMPORT
            {{- end }}
            {{- if Values.eureka_enable }}
            - name: EUREKA_INSTANCE_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: EUREKA_INSTANCE_CLIENT_SERVICE_URL_DEFAULTZONE
            {{- end }}
            {{- if Values.keycloak_enable }}
            - name: SECURITY_OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: SECURITY_OAUTH2_RESOURCE_SERVER_JWT_ISSUER_URI
            {{- end }}
            {{ - if Values.otel_enable }}
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: JAVA_TOOL_OPTIONS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: OTEL_LOGS_EXPORTER
            {{- end }}
            {{- if .Values.rabbitmq_enable}}
            - name: SPRING_CLOUD_STREAM_RABBITMQ_BINDER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.configMap }}
                  key: SPRING_CLOUD_STREAM_RABBITMQ_BINDER_ADDRESSES
            {{- end }}
{{- end -}}


