
deploymentName: cards-service
appLabel: cards
appName: cards
serviceName: cards


replicaCount: 1

image:
  repoName: selva2404/cardservice
  tag: s6

containerPort: 8200

service:
  type: ClusterIP
  port: 8200
  targetPort: 8200

appName_enable: true
profile_enable: true
config_enable: true
eureka_enable: true
keyCloak_enable: false
otel_enable: true
rabbitmq_enable: false