spring:
 application:
  name: "configserver"

 cloud:
  config:
   server:
    git:
     uri: "https://github.com/Selva2404/config-all-service.git/"
     username: "Selva2404"
     password: "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"
     clone-on-start: true

management:
 endpoints:
  web:
   exposure:
    include: "*"

server:
  port: "8000"