spring:
  application:
    name: "loans"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loandb
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: "configserver:http://localhost:8000/"
  profiles:
    active: "qa"
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8100